import {
  evaluateFastApiMigratedSliceSmoke,
  parseFastApiMigratedSliceSmokeArgs,
  summarizeFastApiMigratedSliceSmoke,
  type FastApiMigratedSliceSmokeCase,
  type FastApiMigratedSliceSmokeObservation,
  type FastApiMigratedSliceSmokeResult,
} from "./fastapi-migrated-slice-smoke";

export type {
  FastApiMigratedSliceSmokeCase as FastApiDbUnavailableSmokeCase,
  FastApiMigratedSliceSmokeObservation as FastApiDbUnavailableSmokeObservation,
  FastApiMigratedSliceSmokeResult as FastApiDbUnavailableSmokeResult,
};

export { parseFastApiMigratedSliceSmokeArgs, summarizeFastApiMigratedSliceSmoke };

export function buildFastApiDbUnavailableSmokeCases(): FastApiMigratedSliceSmokeCase[] {
  return [
    {
      name: "ordinary ecdict substitute meaning",
      query: "substitute 是什么意思",
      activeExamTarget: "postgrad",
      expectedStatus: 200,
      expectedAnswerKind: "grounded",
      expectedResolution: "resolved",
      expectedMatchType: "external_dictionary_exact",
      expectedGroundingIncludes: ["substitute"],
      expectedProviderRequest: "absent",
      expectedProviderRequestId: null,
    },
    {
      name: "ordinary ecdict substitute usage wording",
      query: "substitute 怎么用",
      activeExamTarget: "postgrad",
      expectedStatus: 200,
      expectedAnswerKind: "grounded",
      expectedResolution: "resolved",
      expectedMatchType: "external_dictionary_exact",
      expectedGroundingIncludes: ["substitute"],
      expectedProviderRequest: "absent",
      expectedProviderRequestId: null,
    },
    {
      name: "direct compare ecdict fallback",
      query: "restrain和constrain的区别",
      activeExamTarget: "postgrad",
      expectedStatus: 200,
      expectedAnswerKind: "grounded",
      expectedResolution: "resolved",
      expectedLearningIntentTask: "focused_compare",
      expectedGroundingIncludes: ["restrain", "constrain"],
      expectedProviderRequest: "absent",
      expectedProviderRequestId: null,
    },
    {
      name: "broad fragment ecdict fallback",
      query: "re开头cile结尾的单词",
      activeExamTarget: "postgrad",
      expectedStatus: 200,
      expectedAnswerKind: "grounded",
      expectedResolution: "resolved",
      expectedLearningIntentTask: "form_filter",
      expectedGroundingIncludes: ["reconcile"],
      expectedProviderRequest: "absent",
      expectedProviderRequestId: null,
    },
    {
      name: "plain similar-word wording routes broad",
      query: "有个像 institute 的词",
      activeExamTarget: "postgrad",
      expectedStatus: 200,
      expectedAnswerKind: "grounded",
      expectedResolution: "resolved",
      expectedLearningIntentTask: "shape_neighbors",
      expectedProviderRequest: "absent",
      expectedProviderRequestId: null,
    },
    {
      name: "bare connector similar-word wording routes broad",
      query: "\u548ccontest\u50cf\u7684\u5355\u8bcd",
      activeExamTarget: "postgrad",
      expectedStatus: 200,
      expectedAnswerKind: "grounded",
      expectedResolution: "resolved",
      expectedLearningIntentTask: "shape_neighbors",
      expectedProviderRequest: "absent",
      expectedProviderRequestId: null,
    },
    {
      name: "word family respond ecdict fallback",
      query: "respond\u7684\u6d3e\u751f\u8bcd",
      activeExamTarget: "postgrad",
      expectedStatus: 200,
      expectedAnswerKind: "grounded",
      expectedResolution: "resolved",
      expectedLearningIntentTask: "word_family",
      expectedGroundingIncludes: ["respond", "response", "responsive", "responsible"],
      expectedProviderRequest: "absent",
      expectedProviderRequestId: null,
    },
    {
      name: "meaning lookup obey ecdict fallback",
      query: "\u9075\u5b88\u7684\u82f1\u6587\u662f\u5565",
      activeExamTarget: "postgrad",
      expectedStatus: 200,
      expectedAnswerKind: "grounded",
      expectedResolution: "resolved",
      expectedLearningIntentTask: "meaning_core",
      expectedProviderRequest: "absent",
      expectedProviderRequestId: null,
    },
    {
      name: "meaning lookup restrict ecdict fallback",
      query: "\u9650\u5236\u7528\u82f1\u8bed\u600e\u4e48\u8bf4",
      activeExamTarget: "postgrad",
      expectedStatus: 200,
      expectedAnswerKind: "grounded",
      expectedResolution: "resolved",
      expectedLearningIntentTask: "meaning_core",
      expectedProviderRequest: "absent",
      expectedProviderRequestId: null,
    },
    {
      name: "meaning lookup expression obey cleaned hint",
      query: "\u8868\u8fbe\u9075\u5b88\u7684\u5355\u8bcd",
      activeExamTarget: "postgrad",
      expectedStatus: 200,
      expectedAnswerKind: "grounded",
      expectedResolution: "resolved",
      expectedLearningIntentTask: "meaning_core",
      expectedProviderRequest: "absent",
      expectedProviderRequestId: null,
    },
    {
      name: "meaning lookup responsibility ecdict fallback",
      query: "\u8868\u793a\u627f\u62c5\u8d23\u4efb\u7684\u8bcd\u6709\u54ea\u4e9b",
      activeExamTarget: "postgrad",
      expectedStatus: 200,
      expectedAnswerKind: "grounded",
      expectedResolution: "resolved",
      expectedLearningIntentTask: "meaning_core",
      expectedProviderRequest: "absent",
      expectedProviderRequestId: null,
    },
    {
      name: "meaning lookup express opinion ecdict fallback",
      query: "\u8868\u793a\u8868\u8fbe\u89c2\u70b9\u7684\u8bcd\u6709\u54ea\u4e9b\u54ea\u4e9b\u8003\u8bd5\u5e38\u89c1",
      activeExamTarget: "postgrad",
      expectedStatus: 200,
      expectedAnswerKind: "grounded",
      expectedResolution: "resolved",
      expectedLearningIntentTask: "meaning_core",
      expectedProviderRequest: "absent",
      expectedProviderRequestId: null,
    },
    {
      name: "meaning lookup follow ecdict fallback",
      query: "\u9075\u5faa\u7684\u82f1\u6587\u662f\u4ec0\u4e48",
      activeExamTarget: "postgrad",
      expectedStatus: 200,
      expectedAnswerKind: "grounded",
      expectedResolution: "resolved",
      expectedLearningIntentTask: "meaning_core",
      expectedGroundingIncludes: ["follow"],
      expectedMainAnswerIncludes: ["follow"],
      expectedProviderRequest: "absent",
      expectedProviderRequestId: null,
    },
    {
      name: "meaning lookup activity ecdict fallback",
      query: "\u6d3b\u52a8\u7684\u82f1\u6587\u662f\u4ec0\u4e48",
      activeExamTarget: "postgrad",
      expectedStatus: 200,
      expectedAnswerKind: "grounded",
      expectedResolution: "resolved",
      expectedLearningIntentTask: "meaning_core",
      expectedGroundingIncludes: ["activity"],
      expectedMainAnswerIncludes: ["activity"],
      expectedProviderRequest: "absent",
      expectedProviderRequestId: null,
    },
  ];
}

export function evaluateFastApiDbUnavailableSmoke(
  caseDef: FastApiMigratedSliceSmokeCase,
  observation: FastApiMigratedSliceSmokeObservation,
): FastApiMigratedSliceSmokeResult {
  return evaluateFastApiMigratedSliceSmoke(caseDef, observation);
}
